project:
  type: website
  output-dir: docs
  resources: 
    - "*.pdf"

website:
  title: "Augustas Macijauskas"
  favicon: assets/favicon.ico
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/AugustasMacijauskas/
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/augustas-macijauskas/
        target: _blank
      - icon: twitter
        href: https://twitter.com/augustasmac
        target: _blank
  open-graph:
    site-name: "Augustas Macijauskas' blog"
    image: augustas-macijauskas-square-profile.jpg
  google-analytics:
    tracking-id: "G-1M6C1LWNHY"
    storage: cookies
    anonymize-ip: true
  cookie-consent:
    type: implied
format:
  html:
    theme: cosmo
    css: styles.css

comments:
  hypothesis:
    theme: clean
